      contact_name       | gjennomsnitt_per_kunde 
-------------------------+------------------------
 Horst Kloss             |                1282.29
 Jytte Petersen          |                1121.14
 Roland Mendel           |                1028.19
 Mario Pontes            |                1026.29
 Georg Pipps             |                1005.60
 Patricia McKenna        |                 908.73
 Jean Fresnière          |                 902.26
 Jose Pavarotti          |                 899.67
 Howard Snyder           |                 841.25
 Philip Cramer           |                 792.52
 Martine Rancé           |                 729.18
 Paula Wilson            |                 719.69
 Frédérique Citeaux      |                 712.85
 Martín Sommer           |                 705.48
 Ann Devon               |                 702.91
 Karl Jablonski          |                 684.09
 Maria Larsson           |                 657.06
 Michael Holz            |                 644.79
 Lúcia Carvalho          |                 642.94
 Rene Phillips           |                 632.39
 Hari Kumar              |                 623.67
 Pascale Cartrain        |                 617.66
 Elizabeth Lincoln       |                 594.33
 Catherine Dewey         |                 572.71
 Art Braunschweiger      |                 572.08
 Yang Wang               |                 561.31
 Peter Franken           |                 555.34
 Carine Schmitt          |                 528.69
 Anabela Domingues       |                 526.97
 Palle Ibsen             |                 511.09
 Carlos Hernández        |                 505.97
 Isabel de Castro        |                 504.49
 Laurence Lebihan        |                 499.16
 Renate Messner          |                 493.88
 Liz Nixon               |                 480.14
 Christina Berglund      |                 479.38
 Carlos González         |                 472.84
 Felipe Izquierdo        |                 470.76
 Janete Limeira          |                 461.14
 Alexander Feuer         |                 458.38
 Thomas Hardy            |                 446.35
 André Fonseca           |                 442.85
 José Pedro Freyre       |                 440.24
 Henriette Pfalzheim     |                 430.90
 Pirkko Koskitalo        |                 422.94
 Antonio Moreno          |                 413.18
 Dominique Perrier       |                 403.89
 Pedro Afonso            |                 381.07
 Sven Ottlieb            |                 376.32
 Miguel Angel Paolino    |                 372.83
 Manuel Pereira          |                 372.17
 Rita Müller             |                 368.79
 Mary Saveley            |                 367.30
 Jonas Bergulfsen        |                 358.45
 Maria Anders            |                 356.08
 Giovanni Rovelli        |                 341.72
 Karin Josephs           |                 341.30
 Yoshi Latimer           |                 340.36
 Lino Rodriguez          |                 321.37
 Maurizio Moroni         |                 320.37
 Paula Parente           |                 319.38
 Yvonne Moncada          |                 314.56
 Jaime Yorres            |                 307.65
 Fran Wilson             |                 304.19
 Guillermo Fernández     |                 303.01
 Annette Roulet          |                 300.91
 Bernardo Batista        |                 277.70
 Victoria Ashworth       |                 276.81
 Helen Bennett           |                 267.23
 Elizabeth Brown         |                 245.59
 Liu Wong                |                 243.40
 Sergio Gutiérrez        |                 237.01
 Hanna Moos              |                 231.41
 Zbyszek Piestrzeniewicz |                 220.75
 Aria Cruz               |                 216.19
 Matti Karttunen         |                 185.96
 Daniel Tonini           |                 181.10
 Janine Labrune          |                 179.54
 John Steel              |                 178.50
 Helvetius Nagy          |                 174.58
 Patricio Simpson        |                 164.98
 Paolo Accorti           |                 154.57
 Paul Henriot            |                 148.00
 Ana Trujillo            |                 140.29
 Simon Crowther          |                 108.17
 Alejandra Camino        |                 104.81
 Eduardo Saavedra        |                 104.59
 Yoshi Tannamuri         |                  65.31
 Francisco Chang         |                  50.40
(89 rows)

