 product_id | unit_price |           product_name           | units_in_stock |                        description                         |              company_name              |        contact_name        |      phone      
------------+------------+----------------------------------+----------------+------------------------------------------------------------+----------------------------------------+----------------------------+-----------------
          1 |         18 | Chai                             |             39 | Soft drinks, coffees, teas, beers, and ales                | Specialty Biscuits, Ltd.               | Peter Wilson               | (161) 555-4448
          2 |         19 | Chang                            |             17 | Soft drinks, coffees, teas, beers, and ales                | Exotic Liquids                         | Charlotte Cooper           | (171) 555-2222
          3 |         10 | Aniseed Syrup                    |             13 | Sweet and savory sauces, relishes, spreads, and seasonings | Exotic Liquids                         | Charlotte Cooper           | (171) 555-2222
          4 |         22 | Chef Anton's Cajun Seasoning     |             53 | Sweet and savory sauces, relishes, spreads, and seasonings | New Orleans Cajun Delights             | Shelley Burke              | (100) 555-4822
          5 |      21.35 | Chef Anton's Gumbo Mix           |              0 | Sweet and savory sauces, relishes, spreads, and seasonings | New Orleans Cajun Delights             | Shelley Burke              | (100) 555-4822
          6 |         25 | Grandma's Boysenberry Spread     |            120 | Sweet and savory sauces, relishes, spreads, and seasonings | Grandma Kelly's Homestead              | Regina Murphy              | (313) 555-5735
          7 |         30 | Uncle Bob's Organic Dried Pears  |             15 | Dried fruit and bean curd                                  | Grandma Kelly's Homestead              | Regina Murphy              | (313) 555-5735
          8 |         40 | Northwoods Cranberry Sauce       |              6 | Sweet and savory sauces, relishes, spreads, and seasonings | Grandma Kelly's Homestead              | Regina Murphy              | (313) 555-5735
          9 |         97 | Mishi Kobe Niku                  |             29 | Prepared meats                                             | Tokyo Traders                          | Yoshi Nagase               | (03) 3555-5011
         10 |         31 | Ikura                            |             31 | Seaweed and fish                                           | Tokyo Traders                          | Yoshi Nagase               | (03) 3555-5011
         11 |         21 | Queso Cabrales                   |             22 | Cheeses                                                    | Cooperativa de Quesos 'Las Cabras'     | Antonio del Valle Saavedra | (98) 598 76 54
         12 |         38 | Queso Manchego La Pastora        |             86 | Cheeses                                                    | Cooperativa de Quesos 'Las Cabras'     | Antonio del Valle Saavedra | (98) 598 76 54
         13 |          6 | Konbu                            |             24 | Seaweed and fish                                           | Mayumi's                               | Mayumi Ohno                | (06) 431-7877
         14 |      23.25 | Tofu                             |             35 | Dried fruit and bean curd                                  | Mayumi's                               | Mayumi Ohno                | (06) 431-7877
         15 |         13 | Genen Shouyu                     |             39 | Sweet and savory sauces, relishes, spreads, and seasonings | Mayumi's                               | Mayumi Ohno                | (06) 431-7877
         16 |      17.45 | Pavlova                          |             29 | Desserts, candies, and sweet breads                        | Pavlova, Ltd.                          | Ian Devling                | (03) 444-2343
         17 |         39 | Alice Mutton                     |              0 | Prepared meats                                             | Pavlova, Ltd.                          | Ian Devling                | (03) 444-2343
         18 |       62.5 | Carnarvon Tigers                 |             42 | Seaweed and fish                                           | Pavlova, Ltd.                          | Ian Devling                | (03) 444-2343
         19 |        9.2 | Teatime Chocolate Biscuits       |             25 | Desserts, candies, and sweet breads                        | Specialty Biscuits, Ltd.               | Peter Wilson               | (161) 555-4448
         20 |         81 | Sir Rodney's Marmalade           |             40 | Desserts, candies, and sweet breads                        | Specialty Biscuits, Ltd.               | Peter Wilson               | (161) 555-4448
         21 |         10 | Sir Rodney's Scones              |              3 | Desserts, candies, and sweet breads                        | Specialty Biscuits, Ltd.               | Peter Wilson               | (161) 555-4448
         22 |         21 | Gustaf's Knäckebröd              |            104 | Breads, crackers, pasta, and cereal                        | PB Knäckebröd AB                       | Lars Peterson              | 031-987 65 43
         23 |          9 | Tunnbröd                         |             61 | Breads, crackers, pasta, and cereal                        | PB Knäckebröd AB                       | Lars Peterson              | 031-987 65 43
         24 |        4.5 | Guaraná Fantástica               |             20 | Soft drinks, coffees, teas, beers, and ales                | Refrescos Americanas LTDA              | Carlos Diaz                | (11) 555 4640
         25 |         14 | NuNuCa Nuß-Nougat-Creme          |             76 | Desserts, candies, and sweet breads                        | Heli Süßwaren GmbH & Co. KG            | Petra Winkler              | (010) 9984510
         26 |      31.23 | Gumbär Gummibärchen              |             15 | Desserts, candies, and sweet breads                        | Heli Süßwaren GmbH & Co. KG            | Petra Winkler              | (010) 9984510
         27 |       43.9 | Schoggi Schokolade               |             49 | Desserts, candies, and sweet breads                        | Heli Süßwaren GmbH & Co. KG            | Petra Winkler              | (010) 9984510
         28 |       45.6 | Rössle Sauerkraut                |             26 | Dried fruit and bean curd                                  | Plutzer Lebensmittelgroßmärkte AG      | Martin Bein                | (069) 992755
         29 |     123.79 | Thüringer Rostbratwurst          |              0 | Prepared meats                                             | Plutzer Lebensmittelgroßmärkte AG      | Martin Bein                | (069) 992755
         30 |      25.89 | Nord-Ost Matjeshering            |             10 | Seaweed and fish                                           | Nord-Ost-Fisch Handelsgesellschaft mbH | Sven Petersen              | (04721) 8713
         31 |       12.5 | Gorgonzola Telino                |              0 | Cheeses                                                    | Formaggi Fortini s.r.l.                | Elio Rossi                 | (0544) 60323
         32 |         32 | Mascarpone Fabioli               |              9 | Cheeses                                                    | Formaggi Fortini s.r.l.                | Elio Rossi                 | (0544) 60323
         33 |        2.5 | Geitost                          |            112 | Cheeses                                                    | Norske Meierier                        | Beate Vileid               | (0)2-953010
         34 |         14 | Sasquatch Ale                    |            111 | Soft drinks, coffees, teas, beers, and ales                | Bigfoot Breweries                      | Cheryl Saylor              | (503) 555-9931
         35 |         18 | Steeleye Stout                   |             20 | Soft drinks, coffees, teas, beers, and ales                | Bigfoot Breweries                      | Cheryl Saylor              | (503) 555-9931
         36 |         19 | Inlagd Sill                      |            112 | Seaweed and fish                                           | Svensk Sjöföda AB                      | Michael Björn              | 08-123 45 67
         37 |         26 | Gravad lax                       |             11 | Seaweed and fish                                           | Svensk Sjöföda AB                      | Michael Björn              | 08-123 45 67
         38 |      263.5 | Côte de Blaye                    |             17 | Soft drinks, coffees, teas, beers, and ales                | Aux joyeux ecclésiastiques             | Guylène Nodier             | (1) 03.83.00.68
         39 |         18 | Chartreuse verte                 |             69 | Soft drinks, coffees, teas, beers, and ales                | Aux joyeux ecclésiastiques             | Guylène Nodier             | (1) 03.83.00.68
         40 |       18.4 | Boston Crab Meat                 |            123 | Seaweed and fish                                           | New England Seafood Cannery            | Robb Merchant              | (617) 555-3267
         41 |       9.65 | Jack's New England Clam Chowder  |             85 | Seaweed and fish                                           | New England Seafood Cannery            | Robb Merchant              | (617) 555-3267
         42 |         14 | Singaporean Hokkien Fried Mee    |             26 | Breads, crackers, pasta, and cereal                        | Leka Trading                           | Chandra Leka               | 555-8787
         43 |         46 | Ipoh Coffee                      |             17 | Soft drinks, coffees, teas, beers, and ales                | Leka Trading                           | Chandra Leka               | 555-8787
         44 |      19.45 | Gula Malacca                     |             27 | Sweet and savory sauces, relishes, spreads, and seasonings | Leka Trading                           | Chandra Leka               | 555-8787
         45 |        9.5 | Rogede sild                      |              5 | Seaweed and fish                                           | Lyngbysild                             | Niels Petersen             | 43844108
         46 |         12 | Spegesild                        |             95 | Seaweed and fish                                           | Lyngbysild                             | Niels Petersen             | 43844108
         47 |        9.5 | Zaanse koeken                    |             36 | Desserts, candies, and sweet breads                        | Zaanse Snoepfabriek                    | Dirk Luchte                | (12345) 1212
         48 |      12.75 | Chocolade                        |             15 | Desserts, candies, and sweet breads                        | Zaanse Snoepfabriek                    | Dirk Luchte                | (12345) 1212
         49 |         20 | Maxilaku                         |             10 | Desserts, candies, and sweet breads                        | Karkki Oy                              | Anne Heikkonen             | (953) 10956
         50 |      16.25 | Valkoinen suklaa                 |             65 | Desserts, candies, and sweet breads                        | Karkki Oy                              | Anne Heikkonen             | (953) 10956
         51 |         53 | Manjimup Dried Apples            |             20 | Dried fruit and bean curd                                  | G'day, Mate                            | Wendy Mackenzie            | (02) 555-5914
         52 |          7 | Filo Mix                         |             38 | Breads, crackers, pasta, and cereal                        | G'day, Mate                            | Wendy Mackenzie            | (02) 555-5914
         53 |       32.8 | Perth Pasties                    |              0 | Prepared meats                                             | G'day, Mate                            | Wendy Mackenzie            | (02) 555-5914
         54 |       7.45 | Tourtière                        |             21 | Prepared meats                                             | Ma Maison                              | Jean-Guy Lauzon            | (514) 555-9022
         55 |         24 | Pâté chinois                     |            115 | Prepared meats                                             | Ma Maison                              | Jean-Guy Lauzon            | (514) 555-9022
         56 |         38 | Gnocchi di nonna Alice           |             21 | Breads, crackers, pasta, and cereal                        | Pasta Buttini s.r.l.                   | Giovanni Giudici           | (089) 6547665
         57 |       19.5 | Ravioli Angelo                   |             36 | Breads, crackers, pasta, and cereal                        | Pasta Buttini s.r.l.                   | Giovanni Giudici           | (089) 6547665
         58 |      13.25 | Escargots de Bourgogne           |             62 | Seaweed and fish                                           | Escargots Nouveaux                     | Marie Delamare             | 85.57.00.07
         59 |         55 | Raclette Courdavault             |             79 | Cheeses                                                    | Gai pâturage                           | Eliane Noz                 | 38.76.98.06
         60 |         34 | Camembert Pierrot                |             19 | Cheeses                                                    | Gai pâturage                           | Eliane Noz                 | 38.76.98.06
         61 |       28.5 | Sirop d'érable                   |            113 | Sweet and savory sauces, relishes, spreads, and seasonings | Forêts d'érables                       | Chantal Goulet             | (514) 555-2955
         62 |       49.3 | Tarte au sucre                   |             17 | Desserts, candies, and sweet breads                        | Forêts d'érables                       | Chantal Goulet             | (514) 555-2955
         63 |       43.9 | Vegie-spread                     |             24 | Sweet and savory sauces, relishes, spreads, and seasonings | Pavlova, Ltd.                          | Ian Devling                | (03) 444-2343
         64 |      33.25 | Wimmers gute Semmelknödel        |             22 | Breads, crackers, pasta, and cereal                        | Plutzer Lebensmittelgroßmärkte AG      | Martin Bein                | (069) 992755
         65 |      21.05 | Louisiana Fiery Hot Pepper Sauce |             76 | Sweet and savory sauces, relishes, spreads, and seasonings | New Orleans Cajun Delights             | Shelley Burke              | (100) 555-4822
         66 |         17 | Louisiana Hot Spiced Okra        |              4 | Sweet and savory sauces, relishes, spreads, and seasonings | New Orleans Cajun Delights             | Shelley Burke              | (100) 555-4822
         67 |         14 | Laughing Lumberjack Lager        |             52 | Soft drinks, coffees, teas, beers, and ales                | Bigfoot Breweries                      | Cheryl Saylor              | (503) 555-9931
         68 |       12.5 | Scottish Longbreads              |              6 | Desserts, candies, and sweet breads                        | Specialty Biscuits, Ltd.               | Peter Wilson               | (161) 555-4448
         69 |         36 | Gudbrandsdalsost                 |             26 | Cheeses                                                    | Norske Meierier                        | Beate Vileid               | (0)2-953010
         70 |         15 | Outback Lager                    |             15 | Soft drinks, coffees, teas, beers, and ales                | Pavlova, Ltd.                          | Ian Devling                | (03) 444-2343
         71 |       21.5 | Flotemysost                      |             26 | Cheeses                                                    | Norske Meierier                        | Beate Vileid               | (0)2-953010
         72 |       34.8 | Mozzarella di Giovanni           |             14 | Cheeses                                                    | Formaggi Fortini s.r.l.                | Elio Rossi                 | (0544) 60323
         73 |         15 | Röd Kaviar                       |            101 | Seaweed and fish                                           | Svensk Sjöföda AB                      | Michael Björn              | 08-123 45 67
         74 |         10 | Longlife Tofu                    |              4 | Dried fruit and bean curd                                  | Tokyo Traders                          | Yoshi Nagase               | (03) 3555-5011
         75 |       7.75 | Rhönbräu Klosterbier             |            125 | Soft drinks, coffees, teas, beers, and ales                | Plutzer Lebensmittelgroßmärkte AG      | Martin Bein                | (069) 992755
         76 |         18 | Lakkalikööri                     |             57 | Soft drinks, coffees, teas, beers, and ales                | Karkki Oy                              | Anne Heikkonen             | (953) 10956
         77 |         13 | Original Frankfurter grüne Soße  |             32 | Sweet and savory sauces, relishes, spreads, and seasonings | Plutzer Lebensmittelgroßmärkte AG      | Martin Bein                | (069) 992755
(77 rows)

