version: '3.8'

services:
  db:
    image: postgres:latest
    container_name;: devcontainer_postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassord
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: